// Standarddaten für Pokémon-Platin-Randomizer-Nuzlocke
// Wird beim "Neuer Run"-Reset als Basis neu geladen.
// Alle Listen sind im UI editierbar.

const DEFAULT_DATA = {

  checkpoints: [
    { id: 'cp01', type: 'rival',  label: 'Barry – Route 203',        location: 'Route 203',   aceLevel: 9,  completed: false },
    { id: 'cp02', type: 'gym',    label: 'Arena 1 – Veit',           location: 'Erzelingen',  aceLevel: 14, completed: false, gymType: 'Gestein' },
    { id: 'cp03', type: 'gym',    label: 'Arena 2 – Silvana',        location: 'Ewigenau',    aceLevel: 22, completed: false, gymType: 'Pflanze' },
    { id: 'cp04', type: 'gym',    label: 'Arena 3 – Lamina',         location: 'Herzhofen',   aceLevel: 26, completed: false, gymType: 'Geist'   },
    { id: 'cp05', type: 'rival',  label: 'Barry – Route 209',        location: 'Route 209',   aceLevel: 27, completed: false },
    { id: 'cp06', type: 'gym',    label: 'Arena 4 – Hilda',          location: 'Schleiede',   aceLevel: 32, completed: false, gymType: 'Kampf'   },
    { id: 'cp07', type: 'rival',  label: 'Barry – Weideburg',        location: 'Weideburg',   aceLevel: 36, completed: false },
    { id: 'cp08', type: 'gym',    label: 'Arena 5 – Marinus',        location: 'Weideburg',   aceLevel: 37, completed: false, gymType: 'Wasser'  },
    { id: 'cp09', type: 'rival',  label: 'Barry – Fleetburg',        location: 'Fleetburg',   aceLevel: 38, completed: false },
    { id: 'cp10', type: 'gym',    label: 'Arena 6 – Adam',           location: 'Fleetburg',   aceLevel: 41, completed: false, gymType: 'Stahl'   },
    { id: 'cp11', type: 'gym',    label: 'Arena 7 – Frida',          location: 'Blizzach',    aceLevel: 44, completed: false, gymType: 'Eis'     },
    { id: 'cp12', type: 'rival',  label: 'Barry – Speerspitze',      location: 'Speerspitze', aceLevel: 44, completed: false },
    { id: 'cp13', type: 'gym',    label: 'Arena 8 – Volkner',        location: 'Sonnewik',    aceLevel: 50, completed: false, gymType: 'Elektro' },
  ],

  team: [],

  encounters: {
    routes: [
      { id: 'r01',  name: 'Route 201',               species: '', status: 'open' },
      { id: 'r02',  name: 'Route 202',               species: '', status: 'open' },
      { id: 'r03',  name: 'Route 203',               species: '', status: 'open' },
      { id: 'r04',  name: 'Route 204 (Süden)',        species: '', status: 'open' },
      { id: 'r05',  name: 'Route 204 (Norden)',       species: '', status: 'open' },
      { id: 'r06',  name: 'Route 205 (Süden)',        species: '', status: 'open' },
      { id: 'r07',  name: 'Route 205 (Norden)',       species: '', status: 'open' },
      { id: 'r08',  name: 'Route 206',               species: '', status: 'open' },
      { id: 'r09',  name: 'Route 207',               species: '', status: 'open' },
      { id: 'r10',  name: 'Route 208',               species: '', status: 'open' },
      { id: 'r11',  name: 'Route 209',               species: '', status: 'open' },
      { id: 'r12',  name: 'Route 210 (Süden)',        species: '', status: 'open' },
      { id: 'r13',  name: 'Route 210 (Norden)',       species: '', status: 'open' },
      { id: 'r14',  name: 'Route 211 (Osten)',        species: '', status: 'open' },
      { id: 'r15',  name: 'Route 211 (Westen)',       species: '', status: 'open' },
      { id: 'r16',  name: 'Route 212 (Norden)',       species: '', status: 'open' },
      { id: 'r17',  name: 'Route 212 (Süden)',        species: '', status: 'open' },
      { id: 'r18',  name: 'Route 213',               species: '', status: 'open' },
      { id: 'r19',  name: 'Route 214',               species: '', status: 'open' },
      { id: 'r20',  name: 'Route 215',               species: '', status: 'open' },
      { id: 'r21',  name: 'Route 216',               species: '', status: 'open' },
      { id: 'r22',  name: 'Route 217',               species: '', status: 'open' },
      { id: 'r23',  name: 'Route 218',               species: '', status: 'open' },
      { id: 'r24',  name: 'Route 219',               species: '', status: 'open' },
      { id: 'r25',  name: 'Route 220',               species: '', status: 'open' },
      { id: 'r26',  name: 'Route 221',               species: '', status: 'open' },
      { id: 'r27',  name: 'Route 222',               species: '', status: 'open' },
      { id: 'r28',  name: 'Route 223',               species: '', status: 'open' },
      { id: 'r29',  name: 'Route 224',               species: '', status: 'open' },
      { id: 'r30',  name: 'Route 225',               species: '', status: 'open' },
      { id: 'r31',  name: 'Route 226',               species: '', status: 'open' },
      { id: 'r32',  name: 'Route 227',               species: '', status: 'open' },
      { id: 'r33',  name: 'Route 228',               species: '', status: 'open' },
      { id: 'r34',  name: 'Route 229',               species: '', status: 'open' },
      { id: 'r35',  name: 'Route 230',               species: '', status: 'open' },
      { id: 'r36',  name: 'Erzelingen-Tor',           species: '', status: 'open' },
      { id: 'r37',  name: 'Verwüstete Schlucht',      species: '', status: 'open' },
      { id: 'r38',  name: 'Blütenhain-Wiese',         species: '', status: 'open' },
      { id: 'r39',  name: 'Ewigenau-Wald',            species: '', status: 'open' },
      { id: 'r40',  name: 'Altes Herrenhaus',         species: '', status: 'open' },
      { id: 'r41',  name: 'Kronengebirge 1F',         species: '', status: 'open' },
      { id: 'r42',  name: 'Kronengebirge UG1',        species: '', status: 'open' },
      { id: 'r43',  name: 'Kronengebirge (Gipfel)',   species: '', status: 'open' },
      { id: 'r44',  name: 'Irrweg-Höhle',             species: '', status: 'open' },
      { id: 'r45',  name: 'Irrweg-Höhle UG1 (Gible)', species: '', status: 'open' },
      { id: 'r46',  name: 'Prachtmoor',               species: '', status: 'open' },
      { id: 'r47',  name: 'Trostu-Ruinen',             species: '', status: 'open' },
      { id: 'r48',  name: 'Eiseninsel',               species: '', status: 'open' },
      { id: 'r49',  name: 'Wahrhaftsee-Höhle',        species: '', status: 'open' },
      { id: 'r50',  name: 'Ehrsamsee-Höhle',          species: '', status: 'open' },
      { id: 'r51',  name: 'Klarheitssee-Höhle',       species: '', status: 'open' },
      { id: 'r52',  name: 'Siegesstraße',              species: '', status: 'open' },
      { id: 'r53',  name: 'Rückwärts-Höhle',          species: '', status: 'open' },
      { id: 'r54',  name: 'Abschiedsquelle',           species: '', status: 'open' },
      { id: 'r55',  name: 'Frühlingsweg',              species: '', status: 'open' },
      { id: 'r56',  name: 'Sternengebirge (Inneres)',  species: '', status: 'open' },
    ],

    static: [
      { id: 's01', name: 'Driftlon – Kraftwerk Blütenhain',  note: 'Freitags nach Mars-Kampf, Lv 15', species: '', status: 'open' },
      { id: 's02', name: 'Rotom – Altes Herrenhaus',          note: 'Nachts, Lv 20',                   species: '', status: 'open' },
      { id: 's03', name: 'Spiritomb – Heiliger Turm',         note: 'Route 209, Lv 25',                species: '', status: 'open' },
      { id: 's04', name: 'Uxie – Klarheitssee',               note: 'Lv 50',                           species: '', status: 'open' },
      { id: 's05', name: 'Tobutz – Wahrhaftsee',              note: 'Roamend, Lv 50',                  species: '', status: 'open' },
      { id: 's06', name: 'Selfe – Ehrsamsee',                 note: 'Lv 50',                           species: '', status: 'open' },
      { id: 's07', name: 'Giratina – Zerrwelt',               note: 'Lv 47',                           species: '', status: 'open' },
      { id: 's08', name: 'Dialga – Speerspitze',              note: 'Post-Game, Lv 70',                species: '', status: 'open' },
      { id: 's09', name: 'Palkia – Speerspitze',              note: 'Post-Game, Lv 70',                species: '', status: 'open' },
      { id: 's10', name: 'Heatran – Sternengebirge',          note: 'Lv 50',                           species: '', status: 'open' },
      { id: 's11', name: 'Regigigas – Blizzach-Tempel',       note: 'Lv 1',                            species: '', status: 'open' },
      { id: 's12', name: 'Regirock – Felsengipfel-Ruine',     note: 'Lv 30',                           species: '', status: 'open' },
      { id: 's13', name: 'Regice – Eisberg-Ruine',            note: 'Lv 30',                           species: '', status: 'open' },
      { id: 's14', name: 'Registeel – Eisen-Ruine',           note: 'Lv 30',                           species: '', status: 'open' },
      { id: 's15', name: 'Selene – Vollmondinsel',            note: 'Roamend, Lv 50',                  species: '', status: 'open' },
      { id: 's16', name: 'Arktos – Sinnoh (Roamend)',         note: 'Lv 60',                           species: '', status: 'open' },
      { id: 's17', name: 'Zapdos – Sinnoh (Roamend)',         note: 'Lv 60',                           species: '', status: 'open' },
      { id: 's18', name: 'Lavados – Sinnoh (Roamend)',        note: 'Lv 60',                           species: '', status: 'open' },
    ],

    fossils: [
      { id: 'f01', name: 'Schädelstein → Koknodon',    note: 'Untergrund (ungerade Trainer-ID)', species: '', status: 'open' },
      { id: 'f02', name: 'Panzerstein → Schilditas',   note: 'Untergrund (gerade Trainer-ID)',   species: '', status: 'open' },
      { id: 'f03', name: 'Spiralstein → Amonitas',     note: 'Untergrund (nach Nationaldex)',    species: '', status: 'open' },
      { id: 'f04', name: 'Kuppelstein → Kabuto',       note: 'Untergrund (nach Nationaldex)',    species: '', status: 'open' },
      { id: 'f05', name: 'Uralt-Bernstein → Aerodactyl', note: 'Untergrund (nach Nationaldex)', species: '', status: 'open' },
      { id: 'f06', name: 'Klauenstein → Liliep',       note: 'Untergrund (nach Nationaldex)',    species: '', status: 'open' },
      { id: 'f07', name: 'Wurzelstein → Armaldo',      note: 'Untergrund (nach Nationaldex)',    species: '', status: 'open' },
    ],

    honeyTrees: [],
  },

  markets: [
    { id: 'm01', town: 'Sandgemme',  items: [] },
    { id: 'm02', town: 'Jubelstadt', items: [] },
    { id: 'm03', town: 'Erzelingen', items: [] },
    { id: 'm04', town: 'Blütenhain', items: [] },
    { id: 'm05', town: 'Ewigenau',   items: [] },
    { id: 'm06', town: 'Herzhofen',  items: [] },
    { id: 'm07', town: 'Trostu',     items: [] },
    { id: 'm08', town: 'Schleiede',  items: [] },
    { id: 'm09', town: 'Weideburg',  items: [] },
    { id: 'm10', town: 'Fleetburg',  items: [] },
    { id: 'm11', town: 'Blizzach',   items: [] },
    { id: 'm12', town: 'Sonnewik',   items: [] },
  ],

  settings: {
    honeyTreeMax: 3,
  },
};
