// Standarddaten für Pokémon-Platin-Randomizer-Nuzlocke
// Wird beim "Neuer Run"-Reset als Basis neu geladen.
// Alle Listen sind im UI editierbar.

const DEFAULT_DATA = {

  checkpoints: [
    { id: 'cp01', type: 'rival',  label: 'Barry – Route 203',        location: 'Route 203',   aceLevel: 9,  completed: false },
    { id: 'cp02', type: 'gym',    label: 'Arena 1 – Veit',           location: 'Erzelingen',  aceLevel: 14, completed: false, gymType: 'Gestein' },
    { id: 'cp03', type: 'gym',    label: 'Arena 2 – Silvana',        location: 'Ewigenau',    aceLevel: 22, completed: false, gymType: 'Pflanze' },
    { id: 'cp04', type: 'gym',    label: 'Arena 3 – Lamina',         location: 'Herzhofen',   aceLevel: 26, completed: false, gymType: 'Geist'   },
    { id: 'cp05', type: 'rival',  label: 'Barry – Route 209',        location: 'Route 209',   aceLevel: 27, completed: false },
    { id: 'cp06', type: 'gym',    label: 'Arena 4 – Hilda',          location: 'Schleiede',   aceLevel: 32, completed: false, gymType: 'Kampf'   },
    { id: 'cp07', type: 'rival',  label: 'Barry – Weideburg',        location: 'Weideburg',   aceLevel: 36, completed: false },
    { id: 'cp08', type: 'gym',    label: 'Arena 5 – Marinus',        location: 'Weideburg',   aceLevel: 37, completed: false, gymType: 'Wasser'  },
    { id: 'cp09', type: 'rival',  label: 'Barry – Fleetburg',        location: 'Fleetburg',   aceLevel: 38, completed: false },
    { id: 'cp10', type: 'gym',    label: 'Arena 6 – Adam',           location: 'Fleetburg',   aceLevel: 41, completed: false, gymType: 'Stahl'   },
    { id: 'cp11', type: 'gym',    label: 'Arena 7 – Frida',          location: 'Blizzach',    aceLevel: 44, completed: false, gymType: 'Eis'     },
    { id: 'cp12', type: 'rival',  label: 'Barry – Speerspitze',      location: 'Speerspitze', aceLevel: 44, completed: false },
    { id: 'cp13', type: 'gym',    label: 'Arena 8 – Volkner',        location: 'Sonnewik',    aceLevel: 50, completed: false, gymType: 'Elektro' },
    { id: 'cp14', type: 'e4',       label: 'Top 4 – Herbaro',        location: 'Pokémon-Liga', aceLevel: 53, completed: false, gymType: 'Käfer'  },
    { id: 'cp15', type: 'e4',       label: 'Top 4 – Teresa',         location: 'Pokémon-Liga', aceLevel: 55, completed: false, gymType: 'Boden'  },
    { id: 'cp16', type: 'e4',       label: 'Top 4 – Ignaz',          location: 'Pokémon-Liga', aceLevel: 57, completed: false, gymType: 'Feuer'  },
    { id: 'cp17', type: 'e4',       label: 'Top 4 – Kajus',          location: 'Pokémon-Liga', aceLevel: 59, completed: false, gymType: 'Psycho' },
    { id: 'cp18', type: 'champion', label: 'Champion – Cynthia',     location: 'Pokémon-Liga', aceLevel: 62, completed: false },
  ],

  team: [],

  encounters: {
    // Routen in der persönlichen Ablauf-Reihenfolge des Nutzers (Splits 210/211/212, Angel-Orte inkl.).
    // Danach der noch nicht erreichte Rest in v2-Reihenfolge. Seehöhlen weggelassen; Kraterberg = ein Eintrag.
    routes: [
      { id: 'r01', name: 'Wahrheitsufer',        species: '', status: 'open', note: 'Vorplatz See der Wahrheit' },
      { id: 'r02', name: 'Route 201',            species: '', status: 'open' },
      { id: 'r03', name: 'Route 202',            species: '', status: 'open' },
      { id: 'r04', name: 'Route 219',            species: '', status: 'open' },
      { id: 'r05', name: 'Zweiblattdorf',        species: '', status: 'open', note: 'Angeln' },
      { id: 'r06', name: 'Route 204',            species: '', status: 'open' },
      { id: 'r07', name: 'Route 203',            species: '', status: 'open' },
      { id: 'r08', name: 'Erzelingen-Tor',       species: '', status: 'open', note: 'Höhle' },
      { id: 'r09', name: 'Erzelingen-Mine',      species: '', status: 'open', note: 'Höhle' },
      { id: 'r10', name: 'Route 207',            species: '', status: 'open' },
      { id: 'r11', name: 'Verwüsteter Pfad',     species: '', status: 'open', note: 'Höhle' },
      { id: 'r12', name: 'Kraftwerk',            species: '', status: 'open', note: 'Valley Windworks' },
      { id: 'r13', name: 'Route 205',            species: '', status: 'open' },
      { id: 'r14', name: 'Ewigwald',             species: '', status: 'open', note: 'Eterna Forest' },
      { id: 'r15', name: 'Altes Anwesen',        species: '', status: 'open', note: 'Old Chateau' },
      { id: 'r16', name: 'Ewigenau',             species: '', status: 'open', note: 'Angeln' },
      { id: 'r17', name: 'Route 211 (West)',     species: '', status: 'open' },
      { id: 'r18', name: 'Route 206',            species: '', status: 'open' },
      { id: 'r19', name: 'Bizarre Höhle',        species: '', status: 'open', note: 'Wayward Cave' },
      { id: 'r20', name: 'Kraterberg',           species: '', status: 'open', note: 'Mt. Coronet' },
      { id: 'r21', name: 'Route 208',            species: '', status: 'open' },
      { id: 'r22', name: 'Route 209',            species: '', status: 'open' },
      { id: 'r23', name: 'Trostu-Ruinen',        species: '', status: 'open', note: 'Icognito' },
      { id: 'r24', name: 'Turm der Ruhenden',    species: '', status: 'open', note: 'Lost Tower' },
      { id: 'r25', name: 'Route 210 (Süd)',      species: '', status: 'open' },
      { id: 'r26', name: 'Route 215',            species: '', status: 'open' },
      { id: 'r27', name: 'Route 214',            species: '', status: 'open' },
      { id: 'r28', name: 'Maniac-Tunnel',        species: '', status: 'open' },
      { id: 'r29', name: 'Kühnheitsufer',        species: '', status: 'open', note: 'Vorplatz See der Kühnheit' },
      { id: 'r30', name: 'Route 213',            species: '', status: 'open' },
      { id: 'r31', name: 'Weideburg',            species: '', status: 'open', note: 'Stadt – Angeln' },
      { id: 'r32', name: 'Route 212 (Süd)',      species: '', status: 'open' },
      { id: 'r33', name: 'Route 210 (Nord)',     species: '', status: 'open' },
      { id: 'r34', name: 'Elyses',               species: '', status: 'open', note: 'Stadt – Angeln' },
      { id: 'r35', name: 'Route 211 (Ost)',      species: '', status: 'open' },
      { id: 'r36', name: 'Route 218',            species: '', status: 'open' },
      { id: 'r37', name: 'Fleetburg',            species: '', status: 'open', note: 'Stadt – Angeln' },
      { id: 'r38', name: 'Eiseninsel',           species: '', status: 'open', note: 'Iron Island' },
      { id: 'r39', name: 'Feurio-Hütte',         species: '', status: 'open', note: 'Fuego Ironworks' },
      { id: 'r40', name: 'Großmoor',             species: '', status: 'open', note: 'Safari-Zone' },
      { id: 'r41', name: 'Route 212 (Nord)',     species: '', status: 'open' },
      { id: 'r42', name: 'Trophäengarten',       species: '', status: 'open' },
      { id: 'r43', name: 'Route 220',            species: '', status: 'open', note: 'Surfen' },
      { id: 'r44', name: 'Route 221',            species: '', status: 'open' },
      { id: 'r45', name: 'Route 216',            species: '', status: 'open' },
      { id: 'r46', name: 'Route 217',            species: '', status: 'open' },
      { id: 'r47', name: 'Stärkeufer',           species: '', status: 'open', note: 'Vorplatz See der Stärke' },
      { id: 'r48', name: 'Route 222',            species: '', status: 'open' },
      { id: 'r49', name: 'Sonnewik',             species: '', status: 'open', note: 'Stadt – Angeln' },
      { id: 'r50', name: 'Route 223',            species: '', status: 'open', note: 'Surfen' },
      { id: 'r51', name: 'Siegesstraße',         species: '', status: 'open', note: 'Victory Road' },
      { id: 'r52', name: 'Route 224',            species: '', status: 'open', note: 'Post-Game' },
      { id: 'r53', name: 'Route 225',            species: '', status: 'open', note: 'Post-Game' },
      { id: 'r54', name: 'Route 226',            species: '', status: 'open', note: 'Post-Game' },
      { id: 'r55', name: 'Route 227',            species: '', status: 'open', note: 'Post-Game' },
      { id: 'r56', name: 'Kahlberg',             species: '', status: 'open', note: 'Post-Game · Stark Mountain' },
      { id: 'r57', name: 'Route 228',            species: '', status: 'open', note: 'Post-Game' },
      { id: 'r58', name: 'Route 229',            species: '', status: 'open', note: 'Post-Game' },
      { id: 'r59', name: 'Erholungsareal',       species: '', status: 'open', note: 'Post-Game' },
      { id: 'r60', name: 'Route 230',            species: '', status: 'open', note: 'Post-Game' },
      { id: 'r61', name: 'Scheidequelle',        species: '', status: 'open', note: 'Post-Game' },
      { id: 'r62', name: 'Höhle der Umkehr',     species: '', status: 'open', note: 'Post-Game' },
    ],

    static: [
      { id: 's01', name: 'Driftlon – Kraftwerk Blütenhain',  note: 'Freitags nach Mars-Kampf, Lv 15', species: '', status: 'open' },
      { id: 's02', name: 'Rotom – Altes Herrenhaus',          note: 'Nachts, Lv 20',                   species: '', status: 'open' },
      { id: 's03', name: 'Spiritomb – Heiliger Turm',         note: 'Route 209, Lv 25',                species: '', status: 'open' },
      { id: 's04', name: 'Selfe – See der Stärke',            note: 'Lv 50 (Lake Acuity)',             species: '', status: 'open' },
      { id: 's05', name: 'Vesprit – See der Wahrheit',        note: 'Roamend, Lv 50 (Lake Verity)',    species: '', status: 'open' },
      { id: 's06', name: 'Tobutz – See der Kühnheit',         note: 'Lv 50 (Lake Valor)',              species: '', status: 'open' },
      { id: 's07', name: 'Giratina – Zerrwelt',               note: 'Lv 47',                           species: '', status: 'open' },
      { id: 's08', name: 'Dialga – Speerspitze',              note: 'Post-Game, Lv 70',                species: '', status: 'open' },
      { id: 's09', name: 'Palkia – Speerspitze',              note: 'Post-Game, Lv 70',                species: '', status: 'open' },
      { id: 's10', name: 'Heatran – Kahlberg',                note: 'Post-Game, Lv 50',                species: '', status: 'open' },
      { id: 's11', name: 'Regigigas – Blizzach-Tempel',       note: 'Lv 1',                            species: '', status: 'open' },
      { id: 's12', name: 'Regirock – Felsengipfel-Ruine',     note: 'Lv 30',                           species: '', status: 'open' },
      { id: 's13', name: 'Regice – Eisberg-Ruine',            note: 'Lv 30',                           species: '', status: 'open' },
      { id: 's14', name: 'Registeel – Eisen-Ruine',           note: 'Lv 30',                           species: '', status: 'open' },
      { id: 's15', name: 'Cresselia – Vollmondinsel',         note: 'Roamend, Lv 50',                  species: '', status: 'open' },
      { id: 's16', name: 'Arktos – Sinnoh (Roamend)',         note: 'Lv 60',                           species: '', status: 'open' },
      { id: 's17', name: 'Zapdos – Sinnoh (Roamend)',         note: 'Lv 60',                           species: '', status: 'open' },
      { id: 's18', name: 'Lavados – Sinnoh (Roamend)',        note: 'Lv 60',                           species: '', status: 'open' },
    ],

    fossils: [
      { id: 'f01', name: 'Kopffossil → Koknodon',    note: 'Untergrund (ungerade Trainer-ID)', species: '', status: 'open' },
      { id: 'f02', name: 'Panzerfossil → Schilditas', note: 'Untergrund (gerade Trainer-ID)',   species: '', status: 'open' },
      { id: 'f03', name: 'Helixfossil → Amonitas',   note: 'Untergrund (nach Nationaldex)',    species: '', status: 'open' },
      { id: 'f04', name: 'Domfossil → Kabuto',       note: 'Untergrund (nach Nationaldex)',    species: '', status: 'open' },
      { id: 'f05', name: 'Altbernstein → Aerodactyl', note: 'Untergrund (nach Nationaldex)',   species: '', status: 'open' },
      { id: 'f06', name: 'Klauenfossil → Anorith',   note: 'Untergrund (nach Nationaldex)',    species: '', status: 'open' },
      { id: 'f07', name: 'Wurzelfossil → Liliep',    note: 'Untergrund (nach Nationaldex)',    species: '', status: 'open' },
    ],

    honeyTrees: [],

    gifts: [
      { id: 'g01', name: 'Starter (Labor)',             note: 'Prof. Eibisch, Lv 5',    species: '', status: 'open' },
      { id: 'g02', name: 'Togepi-Ei (Cynthia)',         note: 'nach Jupiter, Ewigenau', species: '', status: 'open' },
      { id: 'g03', name: 'Evoli (Lana, Herzhofen)',     note: 'Lv 20',                  species: '', status: 'open' },
      { id: 'g04', name: 'Porygon (Schleiede)',         note: 'Spielhalle, Lv 25',      species: '', status: 'open' },
      { id: 'g05', name: 'Riolu-Ei (Rico, Eiseninsel)', note: 'nach Eiseninsel',        species: '', status: 'open' },
    ],
  },

  markets: [
    { id: 'm01', town: 'Sandgemme',  items: [] },
    { id: 'm02', town: 'Jubelstadt', items: [] },
    { id: 'm03', town: 'Erzelingen', items: [] },
    { id: 'm04', town: 'Blütenhain', items: [] },
    { id: 'm05', town: 'Ewigenau',   items: [] },
    { id: 'm06', town: 'Herzhofen',  items: [] },
    { id: 'm07', town: 'Trostu',     items: [] },
    { id: 'm08', town: 'Schleiede',  items: [] },
    { id: 'm09', town: 'Weideburg',  items: [] },
    { id: 'm10', town: 'Fleetburg',  items: [] },
    { id: 'm11', town: 'Blizzach',   items: [] },
    { id: 'm12', town: 'Sonnewik',   items: [] },
  ],

  settings: {
    honeyTreeMax: 3,
  },
};
